spring:
  application.name:  mgrsystem
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        #        namespace: b2337976-5556-4caa-ad43-8613ccd957c8
        enabled: true
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
          # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
        service: ${spring.application.name}
  datasource:
    # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
    p6spy: true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/mgrsystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
#    host: 192.168.134.140
    host: 127.0.0.1
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
#  virtual-host:/
  redis:
#    host: 192.168.134.140
    host: 127.0.0.1
    database: 0
    port: 6379
    #单机版完
    password: 123456
    #最大空连接数
    maxActive: 10000
    #最大空闲数
    maxIdle: 20
    #最大等待时间
    maxWaitMillis: -1ms
    #超时时间
    timeout: 10000ms
  cache:
    cache-names: menus_cache

# 日志配置
logging:
    config: classpath:logback-spring.xml


mybatis-plus:
  type-aliases-package: org.cwm3.mgrsystem.*.entity
  mapper-locations: org.cwm3.mgrsystem.mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
fastdfs:
  nginx:
#    host: http://192.168.134.140/
    host: http://localhost/




server:
  port: 8085
  servlet:
    session:
      # session超时时间，单位为秒
      timeout: 3600
  compression:
    enabled: true
