spring:
  datasource:
    # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
    p6spy: true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/mgrsystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.134.139
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.134.139
    database: 0
    port: 6379
    password: ''
  cache:
    cache-names: menus_cache
server:
  port: 8082
  compression:
    enabled: true
# 日志配置
logging:
    config: classpath:logback-spring.xml


mybatis-plus:
  type-aliases-package: org.cwm3.mgrsystem.*.entity
  mapper-locations: org.cwm3.mgrsystem.mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
fastdfs:
  nginx:
    host: http://192.168.134.139/
