server:
  port: 8087
spring:
  application:
    name: mailserver
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
